epochs: 100
gpu: cuda:0
lr_decay_patience: 7
early_stop_patience: 15
lr_decay_factor: 0.3
split by: index         
seed: 1
k : 10



task: Styren     #Toluene,Styren
batch_size: 8     #Toluene 64,Styren 8
init_lr: 0.0003
min_lr :  0.0001
weight_decay : 0

DA : False
Freeze : False
Load pretrained model : True


transformer:
  ntoken: 2000
  d_model: 128
  nhead: 8
  d_hid: 512
  nlayers: 3
  dropout: 0      #Toluene 0.05,Styren 0


